run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gosimple
    - goconst
    - gocyclo
    - dupl
    - misspell
    - unconvert
    - prealloc
    - exportloopref
    - sqlclosecheck
    - bodyclose

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/davidsugianto/idp-core
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  dupl:
    threshold: 100

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst
    - path: docs/
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
