apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-core

resources:
  - ../../base

# Production-specific patches
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: idp-core
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: idp-core
                resources:
                  requests:
                    cpu: "200m"
                    memory: "256Mi"
                  limits:
                    cpu: "1000m"
                    memory: "1Gi"

# Production-specific ConfigMap overrides
configMapGenerator:
  - name: idp-core-config
    behavior: merge
    literals:
      - DB_SSLMODE=require

# Image tags for production
images:
  - name: ghcr.io/davidsugianto/idp-core
    newTag: v1.0.0
