apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-core

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

# Common labels
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: internal-developer-platform

# Images (override with kustomize edit set image)
images:
  - name: ghcr.io/davidsugianto/idp-core
    newTag: latest
