apiVersion: v1
kind: Namespace
metadata:
  name: idp-core
  labels:
    app.kubernetes.io/name: idp-core
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: internal-developer-platform
